---
- hosts: nodes
  user: root
  sudo: True
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dse-spark-install.yml
  - include: tasks/start-dse.yml
